# Site settings
title: Yuqi Wang (王宇琪)
header-img: ./img/table.jpg
description: "About me"
email: wyq1997boy@163.com
url: "https://robertwyq.github.io"

# Sidebar settings
sidebar: true
sidebar-about-description: "my heart is in the work"
sidebar-avatar: ./img/head.JPG 

theme: jekyll-theme-midnight